### ISSUE TITLE
Code and Data

### ISSUE THREAD

**Issue by vateye** [SY-Xuan/Pink#1]
When will the code and data released?

**Comment by SY-Xuan** [comment]
Our paper will be released within a week.

**Comment by SY-Xuan** [comment]
The paper now is available at https://arxiv.org/abs/2310.00582.

**Comment by buaachen1993** [comment]
Will the code and training/inference details be released?

**Comment by SY-Xuan** [comment]
We plan to release the code in about a month.

**Comment by Dongping-Chen** [comment]
When will the code be released? I've waited for a month.

**Comment by SY-Xuan** [comment]
Sorry for the late releasing. I am working on the submission of CVPR. After that I will release the code as soon as possible.

**Comment by TicTacToePP** [comment]
Any update on the release time of the data and code?

**Comment by SY-Xuan** [comment]
Within a month. Sorry for the late release. I am busy with my final thesis.

**Comment by GaoXiaoshan** [comment]
Any update on the release time of the data and code?

**Comment by Jeremy-lf** [comment]
waitting...

**Comment by SY-Xuan** [comment]
The code has been released. Sorry for the late.
