### ISSUE TITLE
Is the environment installation package missing?

### ISSUE THREAD

**Issue by Jeremy-lf** [SY-Xuan/Pink#3]
你好，我按照你给的环境安装流程进行了安装，但是执行stages1.sh无法运行，环境是否对呢？我把此处的llava改成pink，还是无法运行，感觉环境漏了很多东西，可以列举一下吗
![image](https://github.com/SY-Xuan/Pink/assets/45171399/feede2fc-6ba9-4959-810b-1d8a68ec3d29)

**Comment by Jeremy-lf** [comment]
可以提供一个requirement.txt吗，很多包之间不兼容，自己一个一个安装太费劲了

**Comment by SY-Xuan** [comment]
Could you provide me with more information?

**Comment by Jeremy-lf** [comment]
> Could you provide me with more information?
![image](https://github.com/SY-Xuan/Pink/assets/45171399/6d44d2c6-899e-41be-8e56-926c486c9f3c)
like this, i don't konw what package i should install, could you provide your environment for this project? thank you very much!

**Comment by Jeremy-lf** [comment]
![image](https://github.com/SY-Xuan/Pink/assets/45171399/5303577d-4684-4e8b-be56-b16c2ba50753)
when i install protobuf, new problem happens

**Comment by Jeremy-lf** [comment]
![image](https://github.com/SY-Xuan/Pink/assets/45171399/8a200863-04e6-4c8d-8027-6029a7d64d33)
你好，我现在想训练预训练，按照你的说明，下载了CC-3M 数据集，如1所示，然后配置了stage1.sh脚本，配置如2所示，然后也使用了llama2，在运行脚本的时候，不明白4这一步是在下载什么呢？然后程序挂了，可以帮忙看一下吗，十分感谢

**Comment by Jeremy-lf** [comment]
![image](https://github.com/SY-Xuan/Pink/assets/45171399/559e8b50-7d09-4d1b-bfec-9b52cccfdebc)
我的cuda版本

**Comment by Jeremy-lf** [comment]
> ![image](https://private-user-images.githubusercontent.com/45171399/326744327-8a200863-04e6-4c8d-8027-6029a7d64d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODE0NDgsIm5iZiI6MTcxNDQ4MTE0OCwicGF0aCI6Ii80NTE3MTM5OS8zMjY3NDQzMjctOGEyMDA4NjMtMDRlNi00YzhkLTgwMjctNjAyOWE3ZDY0ZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEyNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTgxNmQyOTY5ZWM4OGMyMjgzMTMwZDUzYmE2Yjk2ZjI5Y2QxMDczZjQ0ZDk4MTEwYTg4ODJmYzM3NGYzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bSVGX1Jw8XD7eI4UCEK4VgynqCUiJk2o2s8KxmqGfLo) 你好，我现在想训练预训练，按照你的说明，下载了CC-3M 数据集，如1所示，然后配置了stage1.sh脚本，配置如2所示，然后也使用了llama2，在运行脚本的时候，不明白4这一步是在下载什么呢？然后程序挂了，可以帮忙看一下吗，十分感谢

![image](https://github.com/SY-Xuan/Pink/assets/45171399/bb4d39d8-277e-421b-b72a-cb847b9a9cef)
找不到问题出在哪里，可以帮忙看一下吗😃😃😃

**Comment by SY-Xuan** [comment]
Could you give me full log. For now, it is the common output. I cannot give you any useful information. I also think your pytorch version is not correct.

**Comment by Jeremy-lf** [comment]
Thank your reply, it's problem about cuda and cudnn version not compatible, and it works normal
