### ISSUE TITLE
The data download link is invalid

### ISSUE THREAD

**Issue by Jeremy-lf** [SY-Xuan/Pink#4]
COCO dataset link is invalid, and How can I obtain images files corresponding to *.json in LLaVA-158K? The same problem applies to other images as well.
![image](https://github.com/SY-Xuan/Pink/assets/45171399/c5542968-f783-4ebc-a3a4-86ce35ef9b0d)

**Comment by SY-Xuan** [comment]
If you mean you cannot download the COCO dataset. As a widely used dataset, I think COCO can be downloaded easily. I cannot provide you with the download URL of COCO because of the license.
