### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by XiaoMing-dada** [SY-Xuan/Pink#5]
sorry, I couldn't find some files and I have some difficulties understanding the demo operation. What and where is the "pink/Pink-chat" in the file "demo.py"?

**Comment by SY-Xuan** [comment]
You need to modify the path by yourself. 
`python demo.py --checkpoint-path /path/to/pink --llama-path /path/to/llama2`

The checkpoint can be downloaded at https://huggingface.co/SY-Xuan/Pink_base. The llama2 needs to be downloaded manually.
